### ISSUE TITLE
Program name showing in screen top part

### ISSUE THREAD

**Issue by Rontt1** [drweissbrot/cs-hud#105]
Program name showing in screen top part

![kuva](https://github.com/drweissbrot/cs-hud/assets/151652992/b1490bf2-5c25-4359-9fe0-47994af88ef5)

**Comment by drweissbrot** [comment]
I can't reproduce this, tried on fresh Windows 10 and 11 installs.

Which executable causes the title bar to appear, `cs-hud-win.exe` or `cs-hud.exe`?

**Comment by daphob** [comment]
Hi. I have the same issue and all my caster friends too. We are covering the Nantarena LAN (French LAN occuring at the moment). This problem happenned with the latest version of this HUD. 
Here is my process : once the configuration of my HUD settings is done by using "cs-hud-config.exe" and the "cs-hud-win.exe", I launch "cs-hud.exe" and i launch CS2 to connect to a GOTV. And the name of the window of the HUD appears immediately. It does not disappear if I alt+tab out then in or if i click on the icon on the desktop bar. It's weird because everything was working just fine with the previous version. It appeared after I updated everything.

Anyway, keep the good work, you are doing amazing guys and I'm sure you'll find a solution to make it perfect. Thanks again for everything and sorry for my English, it's not my native language.

**Comment by Rontt1** [comment]
I noticed that it does not appear if you dont click the program at all in taskbar. But if you click it once programname stays up until you close it and open it up again. Problem is on the cs-hud.exe.

And yeah I appreciate you guys very much and this is a lifesaver to my casts. Thanks dudes!

**Comment by drweissbrot** [comment]
I'm unfortunately still unable to reproduce this. There was [an update to Electron](https://github.com/electron/electron/releases/tag/v28.1.1) a couple days ago though that sounds a bit like what you two described. I built the HUD with that new version, could you have a look and see if it's still an issue?

https://drive.proton.me/urls/WG68N0V12M#4n5veCz76kpf (files are too big to attach them to a Github issue :D)
@daphob @Rontt1

**Comment by 42Firehawk** [comment]
I was able to replicate the issue with the standard release, but am unable to reproduce with your proton drive version, so I think it's fixed unless someone else is able to replicate with the new version
