### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by supalele** [drweissbrot/cs-hud#121]
Hi!
Sorry to bother, but I tried to set the HUD up follwing to readme file closely. However, when I open a demo and launch the .exe file, I can only see a greenscreen when opening the hud in my browser. Do you have any idea what im doing wrong?

Thanks!

**Comment by Grga031** [comment]
Same problem.

**Comment by drweissbrot** [comment]
From experience this usually happens because the `gamestate_integration_drweissbrot_hud.cfg` isn't in the right spot. To be clear, it should be inside the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg` directory (unless you changed Steam's or the game's install location).  
There should be files like `boot.vcfg`, `gamemode_competitive.cfg`, and `user_keys_default.vcfg` in the same folder.

The file needs to be named exactly `gamestate_integration_drweissbrot_hud.cfg`; maybe there's a `.txt` in there?

The page will also just stay green as long as you're not either watching a demo, watching a live CSTV match, or on a map and in the spectators team. It may also stay green if the warmup hasn't started yet.


If none of that helps: Could you start a demo, open the HUD page in your browser, press `Ctrl`+`Shift`+`J`, then post a screenshot of the console window?

**Comment by supalele** [comment]
Ah amazing, I put it in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg my bad!

**Comment by drweissbrot** [comment]
Good to hear :D

@Grga031 Let me know if this doesn't work for you.

**Comment by Grga031** [comment]
@drweissbrot same thing. Sorry to bother you. My game folder changed with CS2. I put it in old CSGO folder :D
