### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by s1neX1987** [drweissbrot/cs-hud#123]
No show now i dont know why 
![aaaaa](https://github.com/drweissbrot/cs-hud/assets/153979511/4d6f1170-fbb2-4a90-a3be-06daeb9d9eb8)

**Comment by drweissbrot** [comment]
From experience this usually happens because the `gamestate_integration_drweissbrot_hud.cfg` isn't in the right spot. To be clear, it should be inside the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg` directory (unless you changed Steam's or the game's install location).  
There should be files like `boot.vcfg`, `gamemode_competitive.cfg`, and `user_keys_default.vcfg` in the same folder.

The file needs to be named exactly `gamestate_integration_drweissbrot_hud.cfg`; maybe there's a `.txt` in there?


If none of that helps: Could you start a demo, open the HUD page in your browser, press `Ctrl`+`Shift`+`J`, then post a screenshot of the console window?

**Comment by s1neX1987** [comment]
fixed somehow
