### ISSUE TITLE
Bannable?

### ISSUE THREAD

**Issue by sam1e-dev** [drweissbrot/cs-hud#129]
Possibly a stupid question but is this bannable? Since it in some way interacts with the game no?

**Comment by drweissbrot** [comment]
I sure hope it's safe, otherwise I'm in danger :D I've been using it on my main account for years.

On a technical level, the HUD uses Game State Integration, which Valve specifically put in the game for custom HUDs. GSI works by the HUD asking nicely for some data, and the game actively sending out the data that it wants the HUD to have.
