### ISSUE TITLE
Overlay the HUD on top of CS

### ISSUE THREAD

**Issue by pixe71** [drweissbrot/cs-hud#131]
I have a problem the HUD is not displayed in the game, does anyone have a solution please ?

**Comment by drweissbrot** [comment]
To overlay the HUD on top of the game, follow the instructions in the `Fullscreen Windowed` section of the readme: https://github.com/drweissbrot/cs-hud/blob/bcecde36b9d08bfe1b32e995bcbcacd6c716ca4a/readme.md#fullscreen-windowed

**Comment by pixe71** [comment]
I followed the instructions but I only have 1 screen so normally I didn't use win+shift did I?

**Comment by drweissbrot** [comment]
Let's try to find out where exactly the issue is: Try to follow these instructions, and let me know how far you get before something doesn't work.

1. Start the console app (`cs-hud-win.exe`); you should see a Command Prompt.
2. Open http://localhost:31982/hud in your browser; you should see a green page.
3. Run the overlay app (`cs-hud.exe`); you should see some small semi-transparent black corners in the corners of your monitor.
4. Open CS and start playing a demo. Wait at least until a few players have connected, then close the game.
    1. In your browser, you should now see the HUD itself (players etc.).
    2. The overlay should also now show the HUD, instead of the black corners.

**Comment by pixe71** [comment]
I think I know it's step 3 where you have to opencs-hud.exe but the problem is that I can't find this file

**Comment by drweissbrot** [comment]
Ohh, now I understand :D From the [release page](https://github.com/drweissbrot/cs-hud/releases/tag/v2.3.1), download [`cs-hud-win32-x64.zip`](https://github.com/drweissbrot/cs-hud/releases/download/v2.3.1/cs-hud-win32-x64.zip), unpack the ZIP, and it's gonna be in there.

**Comment by pixe71** [comment]
ah it's good it works perfectly

**Comment by pixe71** [comment]
thanks for the help
