### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by s1neX1987** [drweissbrot/cs-hud#134]
hide the green screen i tried with chorma key but it removes some colors on hud

**Comment by drweissbrot** [comment]
You're using an OBS browser source, right? Make sure you've [followed the instructions](https://github.com/drweissbrot/cs-hud/blob/bcecde36b9d08bfe1b32e995bcbcacd6c716ca4a/readme.md#obs-browser-source). Especially the URL, it must be exactly `http://localhost:31982/hud?transparent`. The `?transparent` will remove the green background so that you don't need any chroma keying.
