### ISSUE TITLE
Hud not working Green Screen

### ISSUE THREAD

**Issue by MaxGame1760** [drweissbrot/cs-hud#167]
![image](https://github.com/drweissbrot/cs-hud/assets/149103249/504aab1d-7467-46e9-acd8-8a9edda18088)

**Comment by drweissbrot** [comment]
From experience this usually happens because the `gamestate_integration_drweissbrot_hud.cfg` isn't in the right spot. To be clear, it should be inside the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg` directory (unless you changed Steam's or the game's install location).  
There should be files like `boot.vcfg`, `gamemode_competitive.cfg`, and `user_keys_default.vcfg` in the same folder.

The file needs to be named exactly `gamestate_integration_drweissbrot_hud.cfg`; maybe there's a `.txt` in there?

The page will also just stay green as long as you're not either watching a demo, watching a live CSTV match, or on a map and in the spectators team. It may also stay green if the warmup hasn't started yet.


If none of that helps, could you take another screenshot of the browser console, but making sure there's no `http://127.0.0.1:31982/hud` in the search box? (And same as above, start a demo first)

**Comment by drweissbrot** [comment]
gonna close this one for now, if you're still having trouble, let me know
