### ISSUE TITLE
How do you add workshop maps?

### ISSUE THREAD

**Issue by 1Bulgarian** [drweissbrot/cs-hud#180]
I am running a Counter-Strike Wingman tournament and our map pool consists of de_vandal which is not present in the src/themes/fennec/img/maps directory. How can I add it?

**Comment by drweissbrot** [comment]
## Obtaining Files

First you need to get ahold of some files:
* a screenshot if you want something to show up in the series graph (e.g. the first image from the Workshop page)
* the radar image (needs to be square, usually 1024x1024px) -- if the map has two levels/floors (like Nuke), you'll probably need an image for each
* the radar config file
 
That config file should look vaguely like this (probably with a bit more stuff in there):
```
"de_thera"
{
	"pos_x"			"-85.609764"
	"pos_y"			"2261.8025"
	"scale"			"4.846961"
}
```

### Using VRF
Can't promise this'll work for all maps, but for [de_thera](https://steamcommunity.com/sharedfiles/filedetails/?id=3121217565) at least, I could extract the radar-related files from the map's VPK file using [VRF](https://valveresourceformat.github.io/). The VPK is located in `/path/to/SteamLibrary/steamapps/workshop/content/<workshop_id>`. Open that VPK in VRF's GUI app or use its decompiler, the files you need are (in case of Thera) in the `panorama` and `resource` directories:
```sh
./Decompiler -i /path/to/SteamLibrary/steamapps/workshop/content/730/3121217565/3121217565.vpk -d -f resource -o .
./Decompiler -i /path/to/SteamLibrary/steamapps/workshop/content/730/3121217565/3121217565.vpk -d -f panorama -o .
```
From `panorama/images/overheadmaps`, I got `de_thera_radar_tga.png` and `de_thera_lower1_radar_tga.png`, and from `resource/overviews` I got `de_thera.txt`.


## Create a Theme

You need to [create a theme](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/docs/theming.md) (or do the next steps in the `userspace` directory).

### Radar Config
In your theme's directory, create a `radars.json`, following the format from [fennec's radars.json](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/src/themes/fennec/radars.json), and using the data from the radar config file -- basically, convert the radar config to JSON and write all the values as numbers instead of strings. For Thera, this is what your `radars.json` should look like:
```json
{
	"de_thera": {
		"pos_x": -85.609764,
		"pos_y": 2261.8025,
		"scale": 4.846961,
		"bombA_x": 0.76864165,
		"bombA_y": 0.41467333,
		"bombB_x": 0.22093602,
		"bombB_y": 0.59849364,

		"verticalsections": {
			"lower1": {
				"AltitudeMin": -16384,
				"AltitudeMax": -64
			},
			"default": {
				"AltitudeMin": -64,
				"AltitudeMax": 16384
			}
		}
	}
}
```
Put in whatever you can from the map's radar config file, if one of the values doesn't exist there, it's probably fine :D The `verticalsections` bit will only exist if the radar has two levels.

### Convert Images
The HUD will look for a WebP file for both the radar and the screenshot. An easy way to convert your images to WebP is https://squoosh.app: Drag an image in, select `WebP` in the bottom right, optionally set effort and quality (higher is better for both, I tend to use 6 and 75 for all images), then save the result. (Or use whatever else you like to get WebPs :D)

### Save Images to the Theme
Inside your theme directory, create the subdirectory `img`, and in there the subdirectories `maps` and `radars`.  
Into `maps`, save the screenshot, using the map's name as file name (e.g. `de_thera.webp`).
In `radars`, create another subdirectory `ingame`. Save your radar images to `ingame`. For the default floor, just use the map's name as the filename (e.g. `de_thera.webp`).
If there's a second floor, use the map name plus the floor name, as it's called in the radar config (so for Thera, `de_thera_lower1.webp`).

### Use the Theme
Don't forget to tell the HUD to use the theme by setting it on the config page. If you did everything in the `userspace` directory, skip this :D

let me know if this helped :D

**Comment by 1Bulgarian** [comment]
This was exactly what I was looking for, and I cannot thank you enough. The only thing I can't quite do is make the radar a tiny bit smaller because it kinda goes underneath the left team's name. But this is a problem I'm having only on this particular map, therefore I can just use the default map radar for the time being.

Also thank you for the very quick and VERY detailed response.

Here is also how it looks (ignore my smoke crosshair)
![image](https://github.com/drweissbrot/cs-hud/assets/29731197/3c116f53-5580-470c-9577-fb62596751fb)

**Comment by drweissbrot** [comment]
> The only thing I can't quite do is make the radar a tiny bit smaller

see #127
